＃此工作流程将全新安装节点依赖项，构建源代码并在不同版本的节点上运行测试
＃有关更多信息，请参见：https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
＃多帐号YOUTH_HEADER用＃号替换，其他的用＆替换
名称：青年（中青看点）

上：
  工作流程调度：
  日程：
     -cron：“ 0/15 * * * *”
  手表：
    类型：青年

职位：
  建造：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    环境：
        YOUTH_HEADER：$ {{secrets.YOUTH_HEADER}}
        YOUTH_ARTBODY：$ {{secrets.YOUTH_ARTBODY}}
        YOUTH_REDBODY：$ {{secrets.YOUTH_REDBODY}}
        YOUTH_TIME：$ {{secrets.YOUTH_TIME}}
    脚步：
      -使用：actions / checkout @ v1
      -名称：使用Node.js 12.x
        用途：actions / setup-node @ v1
        和：
          节点版本：12.x
      -名称：npm install
        如果：env.YOUTH_HEADER
        运行：
          npm安装
      -名称：“运行【中青看点极速版】”
        如果：env.YOUTH_HEADER
        运行：
          节点Youth.js
        环境：
          YOUTH_HEADER1：$ {{secrets.YOUTH_HEADER4}}＃必须账号1 body1
            YOUTH_READBODY1：$ {{secrets.YOUTH_READBODY4}}＃必须账号1 body1
            YOUTH_READTIMEBODY1：$ {{secrets.YOUTH_READTIMEBODY4}}＃必须账号1 body1
            YOUTH_WITHDRAWBODY1：$ {{secrets.YOUTH_WITHDRAWBODY4}}＃非必须账号1提现body1
            YOUTH_SHAREBODY1：$ {{secrets.YOUTH_SHAREBODY4}}
            YOUTH_STARTBODY1：$ {{secrets.YOUTH_STARTBODY4}}
            YOUTH_HEADER2：$ {{secrets.YOUTH_HEADER2}}
            YOUTH_READBODY2：$ {{secrets.YOUTH_READBODY2}}
            YOUTH_READTIMEBODY2：$ {{secrets.YOUTH_READTIMEBODY2}}
            YOUTH_WITHDRAWBODY2：$ {{secrets.YOUTH_WITHDRAWBODY2}}
            YOUTH_SHAREBODY2：$ {{secrets.YOUTH_SHAREBODY2}}
            YOUTH_STARTBODY2：$ {{secrets.YOUTH_STARTBODY2}}
            YOUTH_HEADER3：$ {{secrets.YOUTH_HEADER3}}
            YOUTH_READBODY3：$ {{secrets.YOUTH_READBODY3}}
            YOUTH_READTIMEBODY3：$ {{secrets.YOUTH_READTIMEBODY3}}
            YOUTH_WITHDRAWBODY3：$ {{secrets.YOUTH_WITHDRAWBODY3}}
            YOUTH_SHAREBODY3：$ {{secrets.YOUTH_SHAREBODY3}}
            YOUTH_STARTBODY3：$ {{secrets.YOUTH_STARTBODY3}}
            TG_BOT_TOKEN：$ {{secrets.TG_BOT_TOKEN}}＃非必须tg机器人token
            TG_USER_ID：$ {{secrets.TG_USER_ID}}＃非必须tg机器人userId
