name: 中青分享助力1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-16/2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/bigchalizi/Null.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node

      - name: '运行 【中青分享助力1】'
        run: |
          cd ~/js   
          node youthshare1.js
